// clients/web/src/lib/components/SheetSelectionModal.svelte
<script lang="ts">
  import type { FileInspection } from '../engine/excelParser';
  import { parseSelectedSheets } from '../engine/excelParser';
  import type { SongVoteData } from '../types/timetable';
  import {
    Layers,
    FileSpreadsheet,
    Check,
    X,
    AlertCircle,
    Search,
    CheckSquare,
    Square,
    Users,
    Info,
  } from '@lucide/svelte';

  interface Props {
    inspections: FileInspection[];
    existingCount: number;
    onClose: () => void;
    onConfirm: (selectedSongs: SongVoteData[]) => void;
  }

  let { inspections, existingCount, onClose, onConfirm }: Props = $props();

  let allValidSheetKeys = $derived.by(() => {
    const keys: string[] = [];
    for (const f of inspections) {
      for (const s of f.sheets) {
        if (s.isValid) {
          keys.push(`${f.fileId}::${s.sheetName}`);
        }
      }
    }
    return keys;
  });

  let selectedKeys = $state<Set<string>>(new Set());

  $effect(() => {
    selectedKeys = new Set(allValidSheetKeys);
  });

  let searchQuery = $state('');

  let filteredFiles = $derived.by(() => {
    const q = searchQuery.toLowerCase().trim();
    if (!q) return inspections;

    return inspections
      .map(file => {
        const matchingSheets = file.sheets.filter(s => {
          const matchTab = s.sheetName.toLowerCase().includes(q);
          const matchSong = s.songName.toLowerCase().includes(q);
          const matchMember = s.members.some(m => m.toLowerCase().includes(q));
          return matchTab || matchSong || matchMember;
        });

        return {
          ...file,
          sheets: matchingSheets,
        };
      })
      .filter(f => f.sheets.length > 0);
  });

  function handleToggleSheet(key: string) {
    const next = new Set(selectedKeys);
    if (next.has(key)) {
      next.delete(key);
    } else {
      next.add(key);
    }
    selectedKeys = next;
  }

  function handleToggleFile(file: FileInspection) {
    const validFileKeys = file.sheets.filter(s => s.isValid).map(s => `${file.fileId}::${s.sheetName}`);
    const allSelectedInFile = validFileKeys.every(k => selectedKeys.has(k));
    const next = new Set(selectedKeys);

    if (allSelectedInFile) {
      validFileKeys.forEach(k => next.delete(k));
    } else {
      validFileKeys.forEach(k => next.add(k));
    }
    selectedKeys = next;
  }

  function handleSelectAll() {
    selectedKeys = new Set(allValidSheetKeys);
  }

  function handleDeselectAll() {
    selectedKeys = new Set();
  }

  function handleConfirm() {
    const songs = parseSelectedSheets(inspections, selectedKeys, existingCount);
    onConfirm(songs);
    onClose();
  }

  let selectedCount = $derived(selectedKeys.size);
  let multiTabFilesCount = $derived(inspections.filter(f => f.hasMultipleSheets).length);
</script>

<div
  class="modal-overlay"
  onclick={onClose}
  onkeydown={(e) => { if (e.key === 'Escape') onClose(); }}
  role="presentation"
>
  <div
    class="modal-dialog sheet-selection-modal"
    onclick={(e) => e.stopPropagation()}
    onkeydown={(e) => e.stopPropagation()}
    role="dialog"
    aria-modal="true"
    tabindex="-1"
  >
    <!-- Header -->
    <div class="modal-header">
      <div style="display: flex; align-items: center; gap: 10px;">
        <div class="dropzone-icon-well" style="width: 38px; height: 38px;">
          <Layers size={18} color="var(--accent)" />
        </div>
        <div>
          <h3 class="modal-header-title">Phát hiện file Excel có nhiều tab</h3>
          <p style="margin: 0; font-size: 12px; color: var(--text-muted);">
            Tìm thấy {multiTabFilesCount > 0 ? `${multiTabFilesCount} file Excel nhiều tab` : 'các file Excel'}. Chọn các bài cần nhập:
          </p>
        </div>
      </div>
      <button type="button" class="modal-close-btn" onclick={onClose} aria-label="Đóng">
        <X size={16} />
      </button>
    </div>

    <!-- Action Toolbar -->
    <div class="sheet-selection-toolbar">
      <div class="sheet-search-box">
        <Search size={14} class="search-icon" />
        <input
          type="text"
          placeholder="Tìm tên tab, bài hát, thành viên..."
          value={searchQuery}
          oninput={(e) => searchQuery = (e.target as HTMLInputElement).value}
        />
        {#if searchQuery}
          <button
            type="button"
            class="search-clear-btn"
            onclick={() => searchQuery = ''}
            aria-label="Xóa tìm kiếm"
          >
            <X size={12} />
          </button>
        {/if}
      </div>

      <div style="display: flex; align-items: center; gap: 10px;">
        <span class="bento-pill is-active" style="font-size: 11px;">
          Đã chọn: <strong>{selectedCount}</strong> / {allValidSheetKeys.length} tab
        </span>
        <button
          type="button"
          class="bento-btn"
          style="font-size: 11px; padding: 4px 10px;"
          onclick={handleSelectAll}
        >
          Chọn tất cả
        </button>
        <button
          type="button"
          class="bento-btn"
          style="font-size: 11px; padding: 4px 10px;"
          onclick={handleDeselectAll}
        >
          Bỏ chọn tất cả
        </button>
      </div>
    </div>

    <!-- Modal Body: Grouped List by File -->
    <div class="modal-body sheet-selection-body">
      {#if filteredFiles.length === 0}
        <div style="text-align: center; padding: 24px; color: var(--text-muted);">
          <Info size={28} />
          <p style="margin-top: 8px;">Không tìm thấy tab nào khớp với từ khóa "{searchQuery}"</p>
        </div>
      {:else}
        {#each filteredFiles as file (file.fileId)}
          {@const validFileKeys = file.sheets.filter(s => s.isValid).map(s => `${file.fileId}::${s.sheetName}`)}
          {@const selectedInFileCount = validFileKeys.filter(k => selectedKeys.has(k)).length}
          {@const allSelectedInFile = validFileKeys.length > 0 && selectedInFileCount === validFileKeys.length}

          <div class="file-inspection-group">
            <!-- File Header Card -->
            <div class="file-inspection-header">
              <div style="display: flex; align-items: center; gap: 8px;">
                <FileSpreadsheet size={18} color="var(--success)" />
                <strong style="font-size: 13px; color: var(--text-primary);" title={file.fileName}>
                  {file.fileName}
                </strong>
                <span class="bento-pill is-active" style="font-size: 10px; padding: 1px 6px;">
                  {file.sheets.length} tab {file.hasMultipleSheets ? '• Multi-tab' : ''}
                </span>
              </div>

              <div style="display: flex; align-items: center; gap: 8px;">
                <span style="font-size: 11px; color: var(--text-muted);">
                  {selectedInFileCount}/{validFileKeys.length} tab
                </span>
                <button
                  type="button"
                  class="bento-btn"
                  style="font-size: 11px; padding: 3px 8px;"
                  onclick={() => handleToggleFile(file)}
                >
                  {allSelectedInFile ? 'Bỏ chọn file' : 'Chọn cả file'}
                </button>
              </div>
            </div>

            <!-- Tabs Grid in this File -->
            <div class="file-sheets-grid">
              {#each file.sheets as sheet (sheet.sheetName)}
                {@const key = `${file.fileId}::${sheet.sheetName}`}
                {@const isSelected = selectedKeys.has(key)}

                <div
                  class="sheet-item-card {isSelected ? 'selected' : ''} {!sheet.isValid ? 'invalid' : ''}"
                  onclick={() => {
                    if (sheet.isValid) handleToggleSheet(key);
                  }}
                  onkeydown={(e) => {
                    if (e.key === 'Enter' && sheet.isValid) handleToggleSheet(key);
                  }}
                  role="button"
                  tabindex={sheet.isValid ? 0 : -1}
                >
                  <div style="margin-top: 2px;">
                    {#if isSelected}
                      <CheckSquare size={16} color="var(--accent)" />
                    {:else}
                      <Square size={16} color="var(--text-muted)" />
                    {/if}
                  </div>

                  <div style="display: flex; flex-direction: column; gap: 3px; flex: 1; min-width: 0;">
                    <div style="display: flex; align-items: center; justify-content: space-between; gap: 4px;">
                      <span style="font-size: 12px; font-weight: 700; color: var(--text-primary); white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        Tab: {sheet.sheetName}
                      </span>
                      {#if sheet.isValid}
                        <span class="bento-pill" style="font-size: 9px; padding: 1px 5px;">
                          <Users size={10} />
                          <span>{sheet.members.length}</span>
                        </span>
                      {:else}
                        <span style="font-size: 10px; color: var(--danger-text); font-weight: 600;">
                          Sai định dạng
                        </span>
                      {/if}
                    </div>

                    <div style="font-size: 11px; color: var(--text-secondary); white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                      Bài: <strong>{sheet.songName}</strong>
                    </div>

                    {#if sheet.members.length > 0}
                      <div style="font-size: 10px; color: var(--text-muted); white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">
                        ({sheet.members.slice(0, 3).join(', ')}{sheet.members.length > 3 ? ` +${sheet.members.length - 3}` : ''})
                      </div>
                    {/if}
                  </div>
                </div>
              {/each}
            </div>
          </div>
        {/each}
      {/if}
    </div>

    <!-- Footer -->
    <div class="modal-footer" style="justify-content: space-between;">
      <div style="font-size: 12px; color: var(--text-muted); display: flex; align-items: center; gap: 6px;">
        <Info size={14} />
        <span>Các tab không chọn sẽ được bỏ qua.</span>
      </div>

      <div style="display: flex; align-items: center; gap: 10px;">
        <button type="button" class="bento-btn" onclick={onClose}>
          Hủy
        </button>
        <button
          type="button"
          class="bento-btn bento-btn-primary"
          onclick={handleConfirm}
          disabled={selectedCount === 0}
        >
          <Check size={16} />
          <span>Nhập {selectedCount} tab</span>
        </button>
      </div>
    </div>
  </div>
</div>

// src/components/SheetSelectionModal.tsx
import React, { useState, useMemo } from 'react';
import { FileInspection, parseSelectedSheets } from '../services/excelParser';
import { SongVoteData } from '../types/timetable';
import {
  Layers,
  FileSpreadsheet,
  CheckSquare,
  Square,
  Search,
  Check,
  X,
  Users,
  AlertCircle,
  Info,
} from 'lucide-react';

interface SheetSelectionModalProps {
  inspections: FileInspection[];
  existingCount: number;
  onClose: () => void;
  onConfirm: (selectedSongs: SongVoteData[]) => void;
}

export const SheetSelectionModal: React.FC<SheetSelectionModalProps> = ({
  inspections,
  existingCount,
  onClose,
  onConfirm,
}) => {
  // Initialize all valid sheets as selected by default
  const [selectedKeys, setSelectedKeys] = useState<Set<string>>(() => {
    const initial = new Set<string>();
    for (const file of inspections) {
      for (const sheet of file.sheets) {
        if (sheet.isValid) {
          initial.add(`${file.fileId}::${sheet.sheetName}`);
        }
      }
    }
    return initial;
  });

  const [searchQuery, setSearchQuery] = useState('');

  // Total valid sheets across all files
  const allValidSheetKeys = useMemo(() => {
    const keys: string[] = [];
    for (const file of inspections) {
      for (const sheet of file.sheets) {
        if (sheet.isValid) {
          keys.push(`${file.fileId}::${sheet.sheetName}`);
        }
      }
    }
    return keys;
  }, [inspections]);

  // Filtered files based on search
  const filteredFiles = useMemo(() => {
    if (!searchQuery.trim()) return inspections;
    const query = searchQuery.trim().toLowerCase();

    return inspections
      .map(file => {
        const matchingSheets = file.sheets.filter(
          sheet =>
            sheet.sheetName.toLowerCase().includes(query) ||
            sheet.songName.toLowerCase().includes(query) ||
            sheet.members.some(m => m.toLowerCase().includes(query))
        );
        return {
          ...file,
          sheets: matchingSheets,
        };
      })
      .filter(file => file.sheets.length > 0 || file.fileName.toLowerCase().includes(query));
  }, [inspections, searchQuery]);

  // Toggle a single sheet
  const handleToggleSheet = (key: string) => {
    setSelectedKeys(prev => {
      const next = new Set(prev);
      if (next.has(key)) {
        next.delete(key);
      } else {
        next.add(key);
      }
      return next;
    });
  };

  // Toggle all sheets in a specific file
  const handleToggleFile = (file: FileInspection) => {
    const validFileKeys = file.sheets.filter(s => s.isValid).map(s => `${file.fileId}::${s.sheetName}`);
    const allSelectedInFile = validFileKeys.every(k => selectedKeys.has(k));

    setSelectedKeys(prev => {
      const next = new Set(prev);
      if (allSelectedInFile) {
        validFileKeys.forEach(k => next.delete(k));
      } else {
        validFileKeys.forEach(k => next.add(k));
      }
      return next;
    });
  };

  // Global Select / Deselect all
  const handleSelectAll = () => {
    setSelectedKeys(new Set(allValidSheetKeys));
  };

  const handleDeselectAll = () => {
    setSelectedKeys(new Set());
  };

  // Confirm and parse selected sheets
  const handleConfirm = () => {
    const songs = parseSelectedSheets(inspections, selectedKeys, existingCount);
    onConfirm(songs);
    onClose();
  };

  const selectedCount = selectedKeys.size;
  const multiTabFilesCount = inspections.filter(f => f.hasMultipleSheets).length;

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div
        className="modal-dialog sheet-selection-modal"
        onClick={e => e.stopPropagation()}
      >
        {/* Header */}
        <div className="modal-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <div className="sheet-modal-icon-badge">
              <Layers size={20} color="#1a73e8" />
            </div>
            <div>
              <h3 className="modal-header-title">Phát hiện file Excel có nhiều tab</h3>
              <p style={{ margin: 0, fontSize: 12, color: '#64748b' }}>
                Hệ thống tìm thấy {multiTabFilesCount > 0 ? `${multiTabFilesCount} file Excel nhiều tab` : 'các file Excel'}. Vui lòng chọn các tab (bài hát) cần nhập dữ liệu:
              </p>
            </div>
          </div>
          <button className="modal-close-btn" onClick={onClose}>
            <X size={18} />
          </button>
        </div>

        {/* Action Toolbar */}
        <div className="sheet-selection-toolbar">
          <div className="sheet-toolbar-left">
            <div className="sheet-search-box">
              <Search size={14} className="search-icon" />
              <input
                type="text"
                placeholder="Tìm tab, tên bài hoặc thành viên..."
                value={searchQuery}
                onChange={e => setSearchQuery(e.target.value)}
              />
              {searchQuery && (
                <button
                  type="button"
                  className="search-clear-btn"
                  onClick={() => setSearchQuery('')}
                >
                  <X size={12} />
                </button>
              )}
            </div>
          </div>

          <div className="sheet-toolbar-right">
            <span className="sheet-selection-count">
              Đã chọn: <strong>{selectedCount}</strong> / {allValidSheetKeys.length} tab
            </span>
            <button
              type="button"
              className="btn-text-action"
              onClick={handleSelectAll}
            >
              Chọn tất cả
            </button>
            <span style={{ color: '#cbd5e1' }}>|</span>
            <button
              type="button"
              className="btn-text-action"
              onClick={handleDeselectAll}
            >
              Bỏ chọn tất cả
            </button>
          </div>
        </div>

        {/* Modal Body: Grouped List by File */}
        <div className="modal-body sheet-selection-body">
          {filteredFiles.length === 0 ? (
            <div className="sheet-empty-search">
              <Info size={28} color="#94a3b8" />
              <p>Không tìm thấy tab nào khớp với từ khóa "{searchQuery}"</p>
            </div>
          ) : (
            filteredFiles.map(file => {
              const validFileKeys = file.sheets.filter(s => s.isValid).map(s => `${file.fileId}::${s.sheetName}`);
              const selectedInFileCount = validFileKeys.filter(k => selectedKeys.has(k)).length;
              const allSelectedInFile = validFileKeys.length > 0 && selectedInFileCount === validFileKeys.length;

              return (
                <div key={file.fileId} className="file-inspection-group">
                  {/* File Header Card */}
                  <div className="file-inspection-header">
                    <div className="file-info-left">
                      <FileSpreadsheet size={18} className="file-excel-icon" />
                      <span className="file-name-text" title={file.fileName}>
                        {file.fileName}
                      </span>
                      <span className="file-sheets-pill">
                        {file.sheets.length} tab {file.hasMultipleSheets && '• Multi-tab'}
                      </span>
                    </div>

                    <div className="file-info-right">
                      <span className="file-selected-status">
                        Đã chọn {selectedInFileCount}/{validFileKeys.length} tab
                      </span>
                      <button
                        type="button"
                        className="btn-file-toggle"
                        onClick={() => handleToggleFile(file)}
                      >
                        {allSelectedInFile ? 'Bỏ chọn file này' : 'Chọn hết file này'}
                      </button>
                    </div>
                  </div>

                  {/* Tabs List in this File */}
                  <div className="file-sheets-grid">
                    {file.sheets.map(sheet => {
                      const key = `${file.fileId}::${sheet.sheetName}`;
                      const isSelected = selectedKeys.has(key);

                      return (
                        <div
                          key={sheet.sheetName}
                          className={`sheet-item-card ${isSelected ? 'selected' : ''} ${
                            !sheet.isValid ? 'invalid' : ''
                          }`}
                          onClick={() => {
                            if (sheet.isValid) handleToggleSheet(key);
                          }}
                        >
                          <div className="sheet-item-checkbox">
                            {isSelected ? (
                              <CheckSquare size={18} className="checkbox-icon checked" />
                            ) : (
                              <Square size={18} className="checkbox-icon unchecked" />
                            )}
                          </div>

                          <div className="sheet-item-details">
                            <div className="sheet-item-top">
                              <span className="sheet-tab-name">
                                Tab: <strong>{sheet.sheetName}</strong>
                              </span>
                              {sheet.isValid ? (
                                <span className="sheet-member-badge" title={sheet.members.join(', ')}>
                                  <Users size={12} />
                                  <span>{sheet.members.length} thành viên</span>
                                </span>
                              ) : (
                                <span className="sheet-invalid-badge">
                                  <AlertCircle size={12} />
                                  <span>Không đúng định dạng vote</span>
                                </span>
                              )}
                            </div>

                            <div className="sheet-item-bottom">
                              <span className="sheet-song-name">
                                Bài hát: <strong>{sheet.songName}</strong>
                              </span>
                              {sheet.members.length > 0 && (
                                <span className="sheet-member-preview" title={sheet.members.join(', ')}>
                                  ({sheet.members.slice(0, 3).join(', ')}
                                  {sheet.members.length > 3 ? `, +${sheet.members.length - 3}` : ''})
                                </span>
                              )}
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                </div>
              );
            })
          )}
        </div>

        {/* Footer */}
        <div className="modal-footer" style={{ justifyContent: 'space-between' }}>
          <div style={{ fontSize: 12, color: '#64748b', display: 'flex', alignItems: 'center', gap: 6 }}>
            <Info size={14} color="#94a3b8" />
            <span>Các tab không được chọn sẽ được bỏ qua, không nạp vào lịch.</span>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <button type="button" className="btn-gcal-secondary" onClick={onClose}>
              Hủy
            </button>
            <button
              type="button"
              className="btn-gcal-primary"
              onClick={handleConfirm}
              disabled={selectedCount === 0}
            >
              <Check size={16} />
              <span>Nhập {selectedCount} tab đã chọn</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
